### ISSUE TITLE
Translation detections too deep in modelData array?

### ISSUE THREAD

**Issue by egeriis** [googleapis/google-api-php-client#463] opened 2015-01-26 15:17 UTC
I am currently implementing translation detection in my application. While testing the Google API PHP client I seem to have stumbled upon an issue.

To get a glimpse at what `listDetections` returns, I've `var_dump`ed the return value, which is as such:

```
object(Google_Service_Translate_DetectionsListResponse)#23 (6) {
  ["collection_key":protected]=>
  string(10) "detections"
  ["internal_gapi_mappings":protected]=>
  array(0) {
  }
  ["detectionsType":protected]=>
  string(48) "Google_Service_Translate_DetectionsResourceItems"
  ["detectionsDataType":protected]=>
  string(5) "array"
  ["modelData":protected]=>
  array(1) {
    ["data"]=>
    array(1) {
      ["detections"]=>
      array(1) {
        [0]=>
        array(1) {
          [0]=>
          array(3) {
            ["language"]=>
            string(2) "da"
            ["isReliable"]=>
            bool(false)
            ["confidence"]=>
            float(0.024751695)
          }
        }
      }
    }
  }
  ["processed":protected]=>
  array(0) {
  }
}
```

After looking at this I found that this return type, `Google_Service_Translate_DetectionsListResponse`, includes a `getDetections` method. Calling this however, returns and empty array, even though there is a language detection.

So I looked a bit more into how the PHP lib works, and from the looks of it, it seems that the `modelData` is a hash with one key: "data", which then contains a hash with one key: "detections". This seems odd given that the lib seems to query on `modelData[collection_key]` and `collection_key` is set to "detections" for `Google_Service_Translate_DetectionsListResponse`.

Is this a bug or am I looking at it the wrong way?

**Comment by ianbarber** [comment] 2015-02-05 20:08
Yeah, this looks odd. Do you have a small script we could use to repro?

**Comment by egeriis** [comment] 2015-02-06 12:49
This should do?

```php
$client = new Google_Client();
$client->setDeveloperKey('...');
$translate = new Google_Service_Translate($client);
$translations = $translate->translations->listTranslations($this->description, $targetLanguage);
```

**Comment by davidrojo** [comment] 2015-02-20 20:13
Same here, the problem, you can checkt it with this code:

```php
$client = new \Google_Client();
$client->setApplicationName("AutomatedTranslations");
$client->setDeveloperKey(self::GOOGLE_API_KEY);
        
$service = new \Google_Service_Translate($client);
$result = $service->translations->listTranslations('Hola buenos dias', 'en', ['source' => 'es']);
print_r($result); // You can see here that the text is translated

$text = $result->getTranslations();
print_r($text); //  You can see here that getTranslations returns empty array
```

The problem is that the API request is returning the next json.

```json
{
    "data": {
        "translations": [
            {
                "translatedText": "Hallo Welt"
            }
        ]
    }
}
```

An then the Google_Service_Translate_TranslationsListResponse has the next format

```
Google_Service_Translate_TranslationsListResponse Object
(
    [collection_key:protected] => translations
    [internal_gapi_mappings:protected] => Array
        (
        )
    [translationsType:protected] => Google_Service_Translate_TranslationsResource
    [translationsDataType:protected] => array
    [modelData:protected] => Array
        (
            [data] => Array
                (
                    [translations] => Array
                        (
                            [0] => Array
                                (
                                    [translatedText] => Hello good morning
                                )
                        )
                )
            [translations] => Array
                (
                )
        )
    [processed:protected] => Array
        (
            [translations] => 1
        )
)
```

As you can see, the json response is filled into modelData->data->translations, and it should be modelData->translations, this is because the json response has a "data" in the response...

I have quickfixed this overwritting the constructor of Google_Service_Translate_TranslationsListResponse in src/Service/Translate.php at line 337

```php
class Google_Service_Translate_TranslationsListResponse extends Google_Collection
 ....
  function __construct(){
  	if (func_num_args() == 1 && is_array(func_get_arg(0))) {
  		$array = func_get_arg(0);
  		if (count($array) == 1 && isset($array['data'])){
  			// QuickFix if the array has only one element and its name is "data"
  			parent::__construct($array['data']);
  		}	
  		else{
  			parent::__construct(func_get_args());
  		}
  	}
  	else{
  		parent::__construct(func_get_args());
  	}
  }
}
```

**Comment by tegansnyder** [comment] 2015-04-10 00:25
@davidrojo good work. xDebug tracing leads same conclusion. PR #523 has been submitted.

**Comment by tmatsuo** [comment] 2017-01-13 22:29
@bshaffer Can you share some information about how to generate the code in google-api-php-client-services, and where is the generator code, etc so that I will be able to fix this issue, or feel free to take this issue by yourself.

**Comment by bshaffer** [comment] 2017-01-17 22:56
@tmatsuo `google-api-php-client-services` has been generated since this issue, so that is not the problem. I will look into it.

**Comment by bshaffer** [comment] 2017-01-17 23:16
The issue seems to be that the API returns everything wrapped in a `data` property that isn't represented (as far as I can tell) in the [Discovery Doc](https://www.googleapis.com/discovery/v1/apis/translate/v2/rest)

**Comment by bshaffer** [comment] 2017-01-18 00:03
In the meantime, I suggest using the [`google/cloud`](https://github.com/googlecloudplatform/google-cloud-php) library for the [Translate API](http://googlecloudplatform.github.io/google-cloud-php/#/docs/v0.20.1/translate/translateclient):

```php
use Google\Cloud\Translate\TranslateClient;

$translate = new TranslateClient();
$result = $translate->translate($text, ['source' => 'es', 'target' => 'en']);
```

**Comment by tmcdos** [comment] 2019-01-30 14:36
I had the same problem but with **Google_Service_Translate()->detections->detect()** method. The solution by @davidrojo does not work with version **2.2.2** of the library because the constructor is marked as **final** in the parent class so I had to fix the issue in a simpler way
```php
class Google_Service_Translate_DetectionsListResponse extends Google_Collection
{
  ....
  /**
   * @return Google_Service_Translate_DetectionsResourceItems
   */
  public function getDetections()
  {
    return $this->data['detections'];
  }
} 
```

**Comment by jdpedrie** [comment] 2019-06-14 22:48
https://issuetracker.google.com/issues/135272558

**Comment by dwsupplee** [comment] 2019-08-20 21:02
The response is wrapped in the `data` key due to the fact the `dataWrapper` feature is enabled. We should be able to update the generator to check for whether this feature is enabled and accommodate from there.

**Comment by dwsupplee** [comment] 2019-10-22 17:34
For anyone still experiencing this issue, here's a workaround that should do the trick:

```php
$service = new \Google_Service_Translate($client);
$result = $service->translations->listTranslations(
    'Hola buenos dias',
    'en',
    ['source' => 'es']
);

print_r($result->data['translations']);
```

**Comment by tmcdos** [comment] 2019-10-24 09:31
There is even a better workaround:
```php
class myTranslate extends Google_Service_Translate_DetectionsListResponse
{
  public function getMyDetections($obj)
  {
    return $obj->data['detections'];
  }
} 

  $client = new \Google_Client();
  $client->setApplicationName('Language detector');
  $client->setScopes([\Google_Service_Translate::CLOUD_TRANSLATION]);
  $client->setAccessType('offline');
  $client->setAuthConfig(__DIR__.'/google.json');

  $translate = new \Google_Service_Translate($client);
  $request = new \Google_Service_Translate_DetectLanguageRequest();
  $request->setQ($text_to_be_detected);
  $response = $translate->detections->detect($request);
  $proxy = new myTranslate();
  $result = $proxy->getMyDetections($response); 
  $language = $result[0][0]['language'];
  $confidence = $result[0][0]['confidence']; 
```

**Comment by dwsupplee** [comment] 2020-01-17 00:47
Hi all 👋 ,

I wanted to provide an update here. It turns out translation is one of the only APIs using this legacy data wrapper flag, which is now deprecated. Now that [V3 of the translate is now available](https://github.com/googleapis/google-api-php-client-services/blob/77bdb3cb12dd53bf5a0f23c86c0a57c439de77ad/src/Google/Service/Translate.php#L57) and it doesn't use this flag, we have made a decision to not fix this issue. To help summarize workarounds if you need to stick with V2:

- In this library: [ex1](https://github.com/googleapis/google-api-php-client/issues/463#issuecomment-545071589), [ex2](https://github.com/googleapis/google-api-php-client/issues/463#issuecomment-545833217)
- There is a [google/cloud version of translate which does not suffer from this issue](https://github.com/googleapis/google-api-php-client/issues/463#issuecomment-273341104).

We truly apologize for any pain this caused, and hope the workarounds will suffice. If you find your use case requires a closer look to help resolve this, please reach out and we can take a look to help find solutions.

**Closed by dwsupplee** 2020-01-17 00:47 UTC
Labels: external, priority: p2, status: blocked, type: bug
