### ISSUE TITLE
Error when try to upload thumbnail using php 

### ISSUE THREAD

**Issue by jmmedel** [googleapis/google-api-php-client#1953] opened 2020-09-27 14:27 UTC
#### Environment details

  - OS: Windows 10
  - PHP version: PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
  - Package name and version: "google/apiclient": "^2.7"

#### Code example

```php
<?php

/**
 * Sample PHP code for youtube.thumbnails.set
 * See instructions for running these code samples locally:
 * https://developers.google.com/explorer-help/guides/code_samples#php
 *
 * ADDITIONAL NOTES:
 * 1. This sample code uploads a file and can't be executed via this interface.
 *    To test this code, you must run it locally using your own API credentials.
 *    See: https://developers.google.com/explorer-help/guides/code_samples#php
 * 2. This example makes a multipart upload request. We recommend you consider
 *    using resumable uploads instead, particularly if you are transferring
 *    large files or there's a high likelihood of a network interruption or
 *    other transmission failure. For more information, see:
 *    https://developers.google.com/api-client-library/php/guide/media_upload
 */

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
  throw new Exception(sprintf('Please run "composer require google/apiclient:~2.0" in "%s"', __DIR__));
}
require_once __DIR__ . '/vendor/autoload.php';
$client = new Google_Client();
$client->setApplicationName('API code samples');
$client->setScopes([
    'https://www.googleapis.com/auth/youtube.force-ssl',
]);

// TODO: For this request to work, you must replace
//       "YOUR_CLIENT_SECRET_FILE.json" with a pointer to your
//       client_secret.json file. For more information, see
//       https://cloud.google.com/iam/docs/creating-managing-service-account-keys
$credentialsFile = 'C:/laragon/www/How-to-Update-Youtube-Video-thumbnail-using-php/client_secret.json';
$client->setAuthConfig($credentialsFile);
$client->setAccessType('offline');

// Request authorization from the user.
$authUrl = $client->createAuthUrl();
printf("Open this link in your browser:\n%s\n", $authUrl);
print('Enter verification code: ');
$authCode = trim(fgets(STDIN));

// Exchange authorization code for an access token.
$accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
$client->setAccessToken($accessToken);

// Define service object for making API requests.
$service = new Google_Service_YouTube($client);

// TODO: For this request to work, you must replace "YOUR_FILE"
//       with a pointer to the actual file you are uploading.
//       The maximum file size for this operation is 2097152.
$response = $service->thumbnails->set(
  'XO2fhnG61-Q',
  array(
    'data' => file_get_contents("./thumbnail.jpg"),
    'mimeType' => 'application/octet-stream',
    'uploadType' => 'multipart'
  )
);
print_r($response);










```

Error : 

Stack trace:
#0 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Http\REST.php(98): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#1 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#2 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Http\REST.php(61): Google_Task_Runner->run()
#3 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Client.php(879): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_.. in C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Http\REST.php on line 123

Thanks!

**Comment by jdpedrie** [comment] 2020-09-28 14:01
The error data you shared does not include a message indicating what the problem is. Do you have any more detail about what exactly is going wrong?

**Comment by jmmedel** [comment] 2020-09-28 14:17
try to put this on try catch 

Stack trace:
#0 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(168): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(115): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(32): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(55): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\auth\src\Middleware\ScopedAccessTokenMiddleware.php(135): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): Google\Auth\Middleware\ScopedAccessTokenMiddleware->Google\Auth\Middleware\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#7 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#8 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#9 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#10 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#11 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Client.php(330): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#12 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#13 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\guzzlehttp\guzzle\src\Client.php(122): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#14 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\auth\src\HttpHandler\Guzzle6HttpHandler.php(47): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#15 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Http\REST.php(78): Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\Psr7\Request))
#16 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Task\Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#17 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Http\REST.php(61): Google_Task_Runner->run()
#18 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Client.php(879): Google_Http_REST::execute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...', Array, NULL)
#19 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient\src\Google\Service\Resource.php(232): Google_Client->execute(Object(GuzzleHttp\Psr7\Request), 'Google_Service_...')
#20 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\vendor\google\apiclient-services\src\Google\Service\YouTube\Resource\Thumbnails.php(53): Google_Service_Resource->call('set', Array, 'Google_Service_...')
#21 C:\laragon\www\How-to-Update-Youtube-Video-thumbnail-using-php\main.php(59): Google_Service_YouTube_Resource_Thumbnails->set('XO2fhnG61-Q', Array)
#22 {main}

**Comment by jdpedrie** [comment] 2020-09-28 14:19
There is still no error message. The stack trace is useful to a point, but it doesn't tell us what the error actually is. Try `echo $exception->getMessage()`.

**Comment by jmmedel** [comment] 2020-09-28 14:21
cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://youtube.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=XO2fhnG61-Q&uploadType=media

**Comment by bshaffer** [comment] 2023-04-25 00:58
As this issue is over 2 years old, I am closing it as most likely no longer relevant. Please open a new issue if this is not the case.

**Closed by bshaffer** 2023-04-25 00:58 UTC
Labels: type: question
