### ISSUE TITLE
YouTube Live Broadcast API: liveStreamingNotEnabled thrown when enabled.

### ISSUE THREAD

**Issue by zeke0816** [googleapis/google-api-php-client#1851] opened 2020-06-15 14:30 UTC
#### Environment details

  - OS: macOS 10.15.5 & CentOS 7.8
  - PHP version: 7.4.5
  - Package name and version: google/apiclient@2.4.1

#### Steps to reproduce

  1. Follow any `liveBroadcasts` example in the following page: [Use Cases and Code Snippets](https://developers.google.com/youtube/v3/live/code_samples).

#### Code example

```php
$client = new Google_Client();
$client->setApplicationName('API code samples');
$client->setScopes([
    'https://www.googleapis.com/auth/youtube.readonly',
]);

$client->setAuthConfig('YOUR_CLIENT_SECRET_FILE.json');
$client->setAccessType('offline');

// let's assume we have a token saved in the session for now.
$client->setAccessToken($_SESSION['accessToken']);

// Define service object for making API requests.
$service = new Google_Service_YouTube($client);

$queryParams = [
    'broadcastType' => 'all',
    'mine' => true
];

$response = $service->liveBroadcasts->listLiveBroadcasts('snippet,contentDetails,status', $queryParams);
```

#### Issue description

The problem arises on the last line of this example. A `Google_Exception` is thrown with the following identifier: `liveStreamingNotEnabled`. It comes along with [this help link](https://www.youtube.com/features) which takes you to your account features and status.

In my personal case, not only did I have Live Streaming enabled but I also had no strikes whatsoever and have been streaming for years on YouTube. So, I know for a fact that my account is indeed enabled for live streaming.

What did I do? I ditched the PHP client library for that single fetch and went on to try with cURL. Guess what. It worked. I am still using the PHP client library but only to authorize the app, get access tokens, and whatnot. But I have to use cURL whenever I need to fetch stuff from the authorized user's account.

More about this issue is detailed on [this StackOverflow question](https://stackoverflow.com/questions/40506777/youtube-live-broadcast-api-livestreamingnotenabled) that was asked on November 9, 2016 and never answered, even with a 100-point bounty, to this day (June 15, 2020).

**Comment by LindaLawton** [comment] 2020-06-16 06:39
Any chance you want to add the curl request you used that worked?

**Comment by zeke0816** [comment] 2020-06-16 12:08
Yes, of course.

```php
$endpoint = 'https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet,contentDetails,status&broadcastType=all&mine=true&key=[YOUR_API_KEY]';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Accept: application/json',
    'Authorization: Bearer '.$_SESSION['access_token'] // make sure this exists
]);
$output = curl_exec($ch);
curl_close($ch);
$res = json_decode($output, true);
if(isset($res['error'])){
    throw new Google_Exception($res['error']['message']);
}
```

**Comment by fhinkel** [comment] 2020-12-08 13:59
Hi @zeke0816 , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google API PHP client and YouTube tags](https://stackoverflow.com/questions/tagged/google-api-php-client+youtube-api) is most appropriate for design and general troubleshooting.
* [Google Youtube API's public issue tracker](https://issuetracker.google.com/issues/new?component=186600&template=874803) is most appropriate for bugs and unexpected behavior.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-08 13:59 UTC
Labels: type: question
