### ISSUE TITLE
Fatal GuzzleHTTP cURL error 7 with Wordpress website

### ISSUE THREAD

**Issue by jeremyjones999999** [googleapis/google-api-php-client#2078] opened 2021-05-17 20:39 UTC
#### Environment details

  - OS: Debian GNU/Linux
  - PHP version: 7.4
  - Wordpress

I am running into a difficult error on my wordpress website. I am using the Google Drive API. Occasionally on my wordpress site, I would get this 500 server exception. The exception sometimes appears and sometimes disappears. We have tried creating a new service account but the error persists.

This is the exception:

` Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/www/testing.com/wp-content/themes/testingspace/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200 Stack trace: #0 /home/www/testing.com/wp-content/themes/testingspace/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /home/www/testing.com/wp-content/themes/testingspace/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /home/www/testing.com/wp-content/themes/testingspace/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /home/www/testing.com/wp-content/ in /home/www/testing.com/wp-content/themes/testingspace/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200`

Even when it disappears, I still can’t access the Google Drive Account. below is a snippet of my testing code. I listed the relevant functions (getClient, getToolDrive, getDocuments) and the code that was used to call the functions. The connection/authentication part of the code is a straight copy and paste of [google’s quickstart php code for setting up Google Drive API](https://developers.google.com/drive/api/v3/quickstart/php) so it shouldn’t be the problem.

```php
function getClient() {
    $client = new Google_Client();
    $client->setAuthConfig(__DIR__ . "/ tool-dev1283726.json");
    $client->setApplicationName(“Testing”);
    $client->setScopes(Google_Service_Drive::DRIVE);

    return $client;
}

function getToolDrive($service, $user)
{
    // Print the names and IDs for up to 30 files.
    $optParams = array(
    'pageSize' => 30,
    'fields' => 'nextPageToken, files(id, name)'
    );

     $results = $service->files->listFiles($optParams); //exception is thrown here
   
    ...
    return $userFolder;
}

$client = getClient();
$service = new Google_Service_Drive($client);
// echo response text
// If a POST request to self was made, hide all output except the material update.
if(count($_POST) > 0) {
    ob_end_clean();
}
$drive = getToolDrive($service, $current_user->user_login);
```

So how do we fix this exception?  Any help is greatly appreciated! Thanks!

**Comment by saranshdhingra** [comment] 2023-09-15 10:05
Hi @jeremyjones999999 
Apologies for the delay in response on this issue, perhaps you've already solved the issue.

I tried your code snippet and it works fine for me. But like you mentioned it occurs occasionally  on your environment, perhaps this is something related to where you're hosting the wordpress site or something related to the networking setup.

I'll be closing this as I can't reproduce this issue, but please reopen this if you think you need more discussion on this.
Thanks.

**Closed by saranshdhingra** 2023-09-15 10:05 UTC
Labels: type: question, api: drive, env: wordpress
