### ISSUE TITLE
$service->people->updateContact fail

### ISSUE THREAD

**Issue by juancer** [googleapis/google-api-php-client#1803] opened 2020-03-24 11:36 UTC
- OS: Linux centos 7
  - PHP version: 7.3
  - Package name and version: Codeigniter 3 + google-api-php-client-2.4.0

**_#### Steps to reproduce_**

  1. Try to update a contact
  2. Set the values to update
  3. Send the values with the command
  4. Got error from the HTTP REST

**_#### Code example_**

            $service = new Google_Service_PeopleService(loginGoogle());
            $person = new Google_Service_PeopleService_Person();
            $email = new Google_Service_PeopleService_EmailAddress();
            $email->setValue('test2@test.com');
            $person->setEmailAddresses($email);
            $name = new Google_Service_PeopleService_Name();
            $name->setFamilyName('lastnameTest');
            $name->setGivenName('NameTest');
            $person->setNames($name);
            $phone = new Google_Service_PeopleService_PhoneNumber();
            $phone->setValue('+34555666777');
            $phone->setType('mobile');
            $person->setPhoneNumbers($phone);
            $exe = $service->people->updateContact('people/###etagNumber###',$person);

**_#### And i got the following message:_**

An uncaught Exception was encountered
Type: Google_Service_Exception

Message: 

404. That’s an error.

The requested URL /v1/people/ was not found on this server. That’s all we know.

Filename:../third_party/google-api-php-client-2.4.0/src/Google/Http/REST.php

Line Number: 118

Backtrace:

File:../third_party/google-api-php-client-2.4.0/src/Google/Http/REST.php
Line: 94
Function: decodeHttpResponse

File:../third_party/google-api-php-client-2.4.0/src/Google/Task/Runner.php
Line: 176
Function: doExecute

File:../third_party/google-api-php-client-2.4.0/src/Google/Http/REST.php
Line: 58
Function: run

File:../third_party/google-api-php-client-2.4.0/src/Google/Client.php
Line: 842
Function: execute

File:../third_party/google-api-php-client-2.4.0/src/Google/Service/Resource.php
Line: 232
Function: execute

File:../third_party/google-api-php-client-2.4.0/vendor/google/apiclient-services/src/Google/Service/PeopleService/Resource/People.php
Line: 198
Function: call

**Comment by juancer** [comment] 2020-03-25 15:40
@jdpedrie do you think is something wrong with my code or with the endpoint?
Any help will be really appreciated.
Regards

**Comment by jdpedrie** [comment] 2020-03-25 16:03
I assume `###etagNumber###` is a placeholder and not the value you're sending?

**Comment by juancer** [comment] 2020-03-25 16:16
> I assume `###etagNumber###` is a placeholder and not the value you're sending?

Hi @jdpedrie, yes, for example, one of my created contacts is: `#mH32b+4Af1s=`.
I'm not sure if I have to send the etag number or the id of the contact (I got them both when i create the contact), for this contact is: `67f72faa8e3f9039`. But in both cases i receive the same error.
Regards

**Comment by jdpedrie** [comment] 2020-03-25 16:40
It appears there is an issue in the service. Even when using the Try This API tool on the [documentation page](https://developers.google.com/people/api/rest/v1/people/updateContact), I receive an error response. I suggest you [report](https://issuetracker.google.com/issues?q=status:open%20componentid:344199%2B%20type:bug) this as a potential bug and let the team investigate further.

Since the issue isn't related to the API client, I'm going to close it out. I'm sorry I can't resolve it for you, but do open an issue in the bugtracker!

**Closed by jdpedrie** 2020-03-25 16:40 UTC
Labels: type: question
