### ISSUE TITLE
Error: syntax error, unexpected '|', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by igortsev** [googleapis/google-api-php-client#2097] opened 2021-06-28 04:10 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-api-php-client/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+php

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Mac
  - PHP version: 7.4
  - Package name and version:  "google/apiclient": "^2.7", dev-master

#### Steps to reproduce

  1. ...Create a client and try to request site list from Webmaster

#### Code example

```php
        $client = $authentication->getClient();

        $searchConsole = new \Google_Service_SearchConsole($client);

        $searchConsole->sites->listSites();
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by kimosabi77** [comment] 2021-06-28 06:54
I believe this is because psr/cache is coming in at v2 or v3 which only supports php >=8

Force psr/cache by adding this to your composer.json

"psr/cache": "^1.0",

**Comment by bshaffer** [comment] 2021-06-28 19:02
@igortsev are you running install with `--ignore-platform-reqs`, or downloading and including the `google-api-php-client--PHP8.0.zip` version of this package on a system running `PHP < 8.0`? If so, then @kimosabi77 is correct and you need to either force the `1.0` version of `psr/cache` by requiring it in `composer.json`, or downloading the appropriate ZIP for your version of PHP.

If you aren't ignoring platform reqs, we have a different problem.

**Comment by igortsev** [comment] 2021-06-29 16:49
@bshaffer installed via composer --ignore-platform-reqs not used. 7.2 / 7.3 - issue, 8.0+ not problem with that

**Comment by bshaffer** [comment] 2021-06-29 16:50
@igortsev please provide the full error / stack trace so that I know what file / line this is happening on.

**Comment by igortsev** [comment] 2021-06-29 16:51
@bshaffer Will check soon and let you know

**Comment by bshaffer** [comment] 2022-04-22 20:13
This is clearly a syntax error caused by running PHP 8.0 code on PHP < 8.0. Closing because there is no issue in this library.

**Closed by bshaffer** 2022-04-22 20:13 UTC
Labels: type: question
