### ISSUE TITLE
Message: Missing end boundary in multipart body.

### ISSUE THREAD

**Issue by conedie** [googleapis/google-api-php-client#2368] opened 2023-01-18 04:42 UTC
I am trying to upload a pdf file through the google drive api, I have followed the example found in the documentation, but it gives me the following error.

`<p>Type: Google\Service\Exception</p>
	<p>Message: Missing end boundary in multipart body.</p>`

The following is my code.

```php
$filePath = FCPATH.'pdf'.'/3257216.pdf';
$finfo = finfo_open(FILEINFO_MIME_TYPE);
$mime_type = finfo_file($finfo, $filePath);

$client = new Google\Client();
$client->setAuthConfig(APPPATH.'drive/estudiocargasfiles-e971cbe03742.json');
$client->addScope("https://www.googleapis.com/auth/drive");
$service = new Google\Service\Drive($client);
	
$file = new Google\Service\Drive\DriveFile();
$file->setName("3257216.pdf'");
$file->setParents(array("1pB9Z6Ys2dfE0FoXeMvsdfxyY3f4iwIasdfIewHfs1BCjU"));
$file->setDescription('hola');
$file->setMimeType($mime_type);

$result = $service->files->create(
	$file,
	[
		'data' => file_get_contents($filePath),
		'mimeType' => $mime_type,
		'uploadType' => 'resumable'
	]
);
```

**Comment by yash30201** [comment] 2023-03-07 18:40
Hi @conedie, found a similar issue [here](https://stackoverflow.com/questions/45401879/google-drive-api-file-upload-error-missing-end-boundary-in-multipart-body).

File multipart uploads are showcased [here](https://developers.google.com/drive/api/guides/manage-uploads#php). 
Can you please try debugging your file parsing along with check if the mime_type is correct as intended? Here's a list of [mime types](https://developers.google.com/drive/api/guides/mime-types)

**Comment by yash30201** [comment] 2023-06-27 08:38
Hi @conedie 
I'll be closing this ticket for now. Please feel free to reopen this if you feel the issue still persists.
Thanks.

**Closed by yash30201** 2023-06-27 08:38 UTC
Labels: needs more info, api: drive, priority: p3
