### ISSUE TITLE
Error when calling classroom PHP API method: courses.courseWork.list

### ISSUE THREAD

**Issue by drzewinski** [googleapis/google-api-php-client#2100] opened 2021-07-06 13:01 UTC
So I use the Google Classroom PHP API to integrate it with my project. When the user is requested to logging with the google account, I request the following scopes.

Google_Service_Classroom::CLASSROOM_COURSES_READONLY, Google_Service_Classroom::CLASSROOM_ROSTERS_READONLY, Google_Service_Classroom::CLASSROOM_PROFILE_EMAILS, **Google_Service_Classroom::CLASSROOM_COURSEWORK_STUDENTS_READONLY,** Google_Service_Classroom::CLASSROOM_ANNOUNCEMENTS_READONLY

Interesting enough, the accessToken generated returns the following scopes:

Google_Service_Classroom::CLASSROOM_COURSES_READONLY, Google_Service_Classroom::CLASSROOM_ROSTERS_READONLY, Google_Service_Classroom::CLASSROOM_PROFILE_EMAILS, **Google_Service_Classroom::CLASSROOM_STUDENT_SUBMISSIONS_STUDENTS_READONLY,** Google_Service_Classroom::CLASSROOM_ANNOUNCEMENTS_READONLY

The problem is that courses.courseWork.list specifically requires Google_Service_Classroom::CLASSROOM_COURSEWORK_STUDENTS_READONLY, as stated in the [API reference](https://developers.google.com/classroom/reference/rest/v1/courses.courseWork/list).

So as a result I'm getting an error:

```
{
   "error":{
      "code":403,
      "message":"The caller does not have permission",
      "errors":[
         {
            "message":"The caller does not have permission",
            "domain":"global",
            "reason":"forbidden"
         }
      ],
      "status":"PERMISSION_DENIED"
   }
}
```

Am I doing something wrong or this might be an API bug?

**Comment by elvismdev** [comment] 2022-03-04 20:55
@drzewinski Were you able to figure this out? I'm currently experiencing the exact same error in a script that was working as expected just a few days ago. 

Wonder if you found out a solution or the main reason of this `PERMISSION_DENIED` error.

**Comment by saranshdhingra** [comment] 2023-07-05 10:04
Hi @drzewinski 
I apologize for us taking this long to respond to this.

So, I tried the following code snippet and didn't receive an error:
```php
    $service = new Classroom($client);
    $courses = $service->courses->listCourses();
    $courseId = $courses[0]->getId();
    $courseWork = $service->courses_courseWork->listCoursesCourseWork($courseId);
    var_dump($courseWork);
```

The [documentation](https://developers.google.com/classroom/reference/rest/v1/courses.courseWork/list) mentions that the `PERMISSION_DENIED` error comes for a range of cases.

For example, if you're requesting a course that is not yet published as a student, then you'll get this error.

Probably try the same with an account which has the required permissions.
Would also suggest you try the same with the reference pages like [this one](https://developers.google.com/classroom/reference/rest/v1/courses.courseWork/list) as it eliminates possible errors in the PHP library itself.

I will be closing this for now, as I could not reproduce the issue, but please feel free to reopen this if it reoccurs and isn't happening in the reference pages.

**Closed by saranshdhingra** 2023-07-05 10:04 UTC
Labels: type: question
