### ISSUE TITLE
Model::mapTypes issue when opening a Google Sheet file

### ISSUE THREAD

**Issue by ptit6sky** [googleapis/google-api-php-client#2003] opened 2020-11-26 16:43 UTC
Hi,

When I'm trying to open a Google Sheet file I got this error :

`ErrorException: include_once(ACCENT3.php): failed to open stream: No such file or directory in XXXX`

It seems to be related to the `mapTypes` in `Model.php` file.

The only way I found to make it works it's too change this method in `Model.php` file : 

```php
  protected function keyType($key)
  {
    $keyType = $key . "Type";

    // ensure keyType is a valid class
    if (property_exists($this, $keyType) && class_exists($this->$keyType)) {
      return $this->$keyType;
    }
  }
```

to

```php
  protected function keyType($key)
  {
   ....
    if (property_exists($this, $keyType) && @class_exists($this->$keyType)) {
   ....
```

#### Environment details

  - OS: Linux
  - PHP version: 7.0.33
  - Package name and version: 2.7.0

#### Steps to reproduce

  1. Search a file by its name and get the id (Using `Google_Service_Drive->files->listFiles`)
  2. Try to load the file with Google_Services_Sheets->spreadsheets->get with previous id
  3. Then the error occurred

**Comment by saranshdhingra** [comment] 2023-09-11 08:43
Hi @ptit6sky 
Apologies for the late reply on this, perhaps the issue is already fixed for you.

But I tried replicating the issue with the current `google-api-client`. I used the following code to fetch the spreadsheet:
```
$sheetId = "SHEET_ID";
$service = new \Google_Service_Sheets($client);
$feed = $service->spreadsheets->get($sheetId);
echo $feed->getProperties()->getTitle();
```

And I don't see any error. Perhaps there was an intermediate error in one of the releases at the time of your writing...

I will be closing this for now, but please feel free to reopen this if you think the issue still persists.

**Closed by saranshdhingra** 2023-09-11 08:43 UTC
Labels: type: question, api: sheets
