### ISSUE TITLE
Composer install/update: Could not delete ....

### ISSUE THREAD

**Issue by FabianKoestring** [googleapis/google-api-php-client#1665] opened 2019-06-13 11:34 UTC
Hey there,

everytime we running `composer update` or `composer install` we have to remove the folder by hand. Anybody got an idea what the problem is? 

#### Environment details

  - OS:
       - Host: Windows 10
       - Docker-Container: Alpine
  - PHP version: 7.1.14
  - Package name and version: google/apiclient-services v0.102

#### Steps to reproduce

  1. `composer install` or `composer update`

#### Code example
```console
- Updating google/apiclient-services (v0.101 => v0.102):
  Update failed (Could not delete /vendor/google/apiclient-services/src/Google/Service/Compute: )
  Would you like to try reinstalling the package instead [yes]? yes
- Removing google/apiclient-services (v0.101)

[RuntimeException] Could not delete /vendor/google/apiclient-services/src/Google/Service/Compute:

```

Thanks!

**Comment by jdpedrie** [comment] 2019-06-13 21:11
Are you running composer within docker or on the host machine? If you mix the two, you may encounter permissions issues which will prevent your deleting the files. If you ensure you always run composer in the same context, does the issue resolve itself?

**Comment by FabianKoestring** [comment] 2019-06-14 05:50
> Are you running composer within docker or on the host machine? If you mix the two, you may encounter permissions issues which will prevent your deleting the files. If you ensure you always run composer in the same context, does the issue resolve itself?

We always run `composer` in the docker container. The problem only occurs with this package and we have a lot of dependencies. 😢

**Comment by pfuhrmann** [comment] 2019-08-13 15:09
Same issue here. We have tried also following to run in the VM:

`sudo rm ./vendor`
`composer install`
`composer require google/apiclient:"^2.0"`

Still, same error although as you can see, context is the same. This is indeed related to permissions, but the issue is somewhere in this package.

**Comment by UnnitMetaliya** [comment] 2019-10-21 15:09
I had the same issue. Weirdly, it seemed like related to permissions. 

Try doing this.

`chmod -R 777 vendor`

And, then run `composer install` or `composer update`

I guess by default vendor has 777 permission, but still, welcome to world of PHP! :/

**Comment by jdpedrie** [comment] 2019-11-07 18:54
I'm going to close this issue out. If you're still having trouble, please feel free to re-open! Hopefully the solution suggested by @UnnitMetaliya works for everybody. :)

**Closed by jdpedrie** 2019-11-07 18:54 UTC
Labels: type: question

**Comment by KoenNL** [comment] 2020-02-17 10:34
Even though this issue has been closed, I'd thought I'd contribute.

I ran into the same issue and when I went looking for the problem I'd noticed that the PHP version set in composer.json (PHP 7.2) did not match the PHP version that was actually installed (7.4). I was able to fix it by simply setting the PHP version to the actual version and re-running require command.

Hope this helps.

**Comment by Romerolweb** [comment] 2020-09-09 14:04
> I had the same issue. Weirdly, it seemed like related to permissions.
> 
> Try doing this.
> 
> `chmod -R 777 vendor`
> 
> And, then run `composer install` or `composer update`
> 
> I guess by default vendor has 777 permission, but still, welcome to world of PHP! :/



chmod: cambiando los permisos de 'vendor/EVERY-PACKAGE-ANME': Permission denied

**Comment by Romerolweb** [comment] 2020-09-09 14:04
It is the message.
Is it problem from composer?

**Comment by jksaaltigani** [comment] 2021-03-15 15:36
[RuntimeException]
  Could not delete C:\xampp\htdocs\project\new-project/vendor/composer/a37b3b46\thephpleague-oauth1-client-1e7e6be\re
  sources\examples\tumblr.php:
  This can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed

**Comment by foremtehan** [comment] 2022-09-20 15:18
docker exec mycontainer composer install : 
 
 131/132 [===========================>]  99%    Install of google/apiclient-services failed
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details

In Process.php line 1204:

  The process "'/usr/bin/unzip' -qq '/var/www/html/vendor/composer/tmp-8939db3d0282af9420cd73a5c1fb7b25' -d '/var/www
  /html/vendor/composer/c467eb34'" exceeded the timeout of 300 seconds.

**Comment by bshaffer** [comment] 2022-11-07 16:00
What happened is it took too long (+300s) to download the library (it's rather large). You may need to increase your composer timeout, or find a better internet connection.

**Comment by jeka-corvus** [comment] 2022-11-07 16:19
> What happened is it took too long (+300s) to download the library (it's rather large). You may need to increase your composer timeout, or find a better internet connection.

Thank you. The following helped me
`COMPOSER_PROCESS_TIMEOUT=2000 composer install`

**Comment by nopedev** [comment] 2023-01-13 14:12
temporary solution
```
# in docker
COMPOSER_PROCESS_TIMEOUT=2000 composer install

# out of docker
repeat 1000 chmod -R 0777 vendor/composer && sleep 1
```

**Comment by outfree** [comment] 2023-10-04 11:06
> > This can be due to an antivirus or the Windows Search Indexer locking the file while they are analyzed
> 
> That fixed it, thanks!

@casperbrands How you fixed that - can you reply?

**Comment by roshanlp56** [comment] 2024-08-27 09:32
> temporary solution
> 
> ```
> # in docker
> COMPOSER_PROCESS_TIMEOUT=2000 composer install
> 
> # out of docker
> repeat 1000 chmod -R 0777 vendor/composer && sleep 1
> ```

Thanks "COMPOSER_PROCESS_TIMEOUT" worked. Although temporarily, it worked.
