### ISSUE TITLE
Get list of members subscribed in Youtube Channel

### ISSUE THREAD

**Issue by sunildabhi** [googleapis/google-api-php-client#1919] opened 2020-08-25 11:12 UTC
i am trying to get list of all members which is subscribed to my youtube channel but i am getting below error:

Fatal error: Uncaught Google_Service_Exception: { "error": { "code": 403, "message": "Access forbidden. The request may not be properly authorized.", "errors": [ { "message": "Access forbidden. The request may not be properly authorized.", "domain": "youtube.common", "reason": "forbidden" } ] } } in /home/bkdharidham/public_html/ytb/vendor/google/apiclient/src/Google/Http/REST.php:118 Stack trace: #0 /home/bkdharidham/public_html/ytb/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 /home/bkdharidham/public_html/ytb/vendor/google/apiclient/src/Google/Task/Runner.php(181): Google_Http_REST::doExecute(Object(GuzzleHttp\Client), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #2 /home/bkdharidham/public_html/ytb/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run() #3 /home/bkdharidham/public_html/ytb/vend in /home/bkdharidham/public_html/ytb/vendor/google/apiclient/src/Google/Http/REST.php on line 118

here is code i am using:

```
if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    throw new Exception(sprintf('Please run "composer require google/apiclient:~2.0" in "%s"', __DIR__));
}
require_once __DIR__ . '/vendor/autoload.php';

$client = new Google_Client();
$client->setApplicationName('API code samples');
$client->setScopes([
    'https://www.googleapis.com/auth/youtube.readonly',
]);

// TODO: For this request to work, you must replace
//       "YOUR_CLIENT_SECRET_FILE.json" with a pointer to your
//       client_secret.json file. For more information, see
//       https://cloud.google.com/iam/docs/creating-managing-service-account-keys
$client->setAuthConfig('client_secret.json');
$client->setAccessType('offline');

if (isset($_GET['code']) && $_GET['code'] != '') {
    $authCode = $_GET['code'];

// Exchange authorization code for an access token.
    $accessToken = $client->fetchAccessTokenWithAuthCode($authCode);
    $client->setAccessToken($accessToken);

// Define service object for making API requests.
    $service = new Google_Service_YouTube($client);

    $response = $service->members->listMembers('snippet');
    print_r($response);
} else {
// Request authorization from the user.
    $authUrl = $client->createAuthUrl();
    header('location:' . $authUrl);
}
```
Please help me how can i get it.

**Comment by fhinkel** [comment] 2020-12-08 14:03
Hi @sunildabhi , thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google API PHP client and YouTube tags](https://stackoverflow.com/questions/tagged/google-api-php-client+youtube-api) is most appropriate for design and general troubleshooting.
* [Google Youtube API's public issue tracker](https://issuetracker.google.com/issues/new?component=186600&template=874803) is most appropriate for bugs and unexpected behavior.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-12-08 14:03 UTC
Labels: type: question
