### ISSUE TITLE
How to resolve 403 forbidden issue when trying to use Google Android Play API (androidpublisher.reviews.list) to get android app reviews

### ISSUE THREAD

**Issue by ankitsakhareliya** [googleapis/google-api-php-client#1688] opened 2019-08-09 13:17 UTC
When I try to get my app reviews by following Google Android Play API with owner access, it shows me an exception "You do not have permission to execute this method." every time.

1) Google AIP explorer https://developers.google.com/apis-explorer/?hl=en_US#p/androidpublisher/v3/androidpublisher.reviews.list (Exception: https://prnt.sc/oqjbto)

2) PHP Google-API library https://github.com/googleapis/google-api-php-client (Exception: http://prntscr.com/oqjc2g)

Please post your suggestion here, If anyone resolved that type of issue

Thank you!

**Comment by jdpedrie** [comment] 2019-08-09 15:59
Please share a code sample demonstrating the issue (with identifying information redacted) and authentication scopes used.

**Comment by ankitsakhareliya** [comment] 2019-08-12 03:52
Hello @jdpedrie 

Thank you for your reply!

I have attached code with both method like "Auth with access token (AuthWithAccessToken.php)" and "Auth with private key (AuthWithPrivateKey.php)"
 
scope I used for get app review : https://www.googleapis.com/auth/androidpublisher

Description:
AuthWithAccessToken.php
- in this file user have to auth with google first then i used "Google_Service_AndroidPublisher" method for get app review.

AuthWithPrivateKey.php
- In this file i created new "Service account keys" and downloaded "client.json" on console google and then i configure json file in library then i used "Google_Service_AndroidPublisher" method for get app review.

I used both method and try to get app reviews but every time it returns : 
{
error: {
	errors: [
		{
			domain: "global",
			reason: "forbidden",
			message: "Forbidden"
		}
	],
	code: 403,
	message: "Forbidden"
	}
}

[code.zip](https://github.com/googleapis/google-api-php-client/files/3490980/code.zip)

**Comment by jdpedrie** [comment] 2019-08-12 14:30
Are you able to access the reviews using a manually-generated access token?

Try it, it'll show us whether the issue is in your auth flow or further downstream.

1. Visit the [OAuth 2.0 Playground](https://developers.google.com/oauthplayground/).
2. Enter the scope you need at the bottom (`https://www.googleapis.com/auth/androidpublisher`).
3. Walk through the auth flow and click the "Exchange authorization code for tokens" button, then copy the access token.

Execute the following code, replacing the dummy access token with the token you generated:

```php
<?php
  require_once __DIR__ . '/vendor/autoload.php';
  session_start();
  date_default_timezone_set('America/Los_Angeles');
    
  $SCOPES = array(
  	  'https://www.googleapis.com/auth/androidpublisher',
  );
  
  $client = new Google_Client();
  $client->setScopes($SCOPES);

  // Put your access token here.
  $client->setAccessToken('ACCESS TOKEN');
  
try {
	$review = new Google_Service_AndroidPublisher($client);

	$opt_param = array();
	$reviews = $review->reviews->listReviews('PackageName', $opt_param);
}
catch (exception $e) {
	echo '<pre>';
	print_r($e->getMessage());
	exit;
}
```

**Comment by ankitsakhareliya** [comment] 2019-08-13 04:15
Hello @jdpedrie 
Thanks for reply!

I followed what you suggest and generate access token on OAuth 2.0 Playground and copy token and set in my code but have same error occur.

Steps screenshots: 
Step 1 : http://prntscr.com/orw9j8
Step 2 : http://prntscr.com/orw9u7
Step 3 : http://prntscr.com/orwaf6
Step 4 : http://prntscr.com/orwbj5
Step 5 : http://prntscr.com/orwdng
Step 6 : http://prntscr.com/orwc1h 
Step 7 : http://prntscr.com/orwii0

Thanks

**Comment by myboopathiraja** [comment] 2019-11-06 04:45
HI..make sure ,you have updated the billing information ,if you  have created GCP project

**Comment by tmatsuo** [comment] 2019-12-05 20:29
@ankitsakhareliya Did you get a chance to follow the advise made by @myboopathiraja ?

**Comment by yokochi** [comment] 2019-12-21 04:43
I think there is a mistake in how to create an service account.
see below link
https://developers.google.com/android-publisher/getting_started#using_a_service_account

https://play.google.com/apps/publish/#ApiAccessPlace
Click Grant Access to provide the service account the necessary rights to perform actions.

For your reference.

**Comment by fhinkel** [comment] 2020-12-08 10:03
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-08 10:03 UTC
Labels: type: question
