### ISSUE TITLE
API My Business

### ISSUE THREAD

**Issue by lsbescorpion** [googleapis/google-api-php-client#2007] opened 2020-12-01 01:36 UTC
I am trying to create a location in my business of the type CUSTOMER_LOCATION_ONLY that is only services areas and I get this error

```
Google\Service\Exception: {
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
```

This is my code.
```
$client = new \Google_Client();
		$client->setAuthConfig($credential);
		$client->addScope('https://www.googleapis.com/auth/business.manage');
		$client->setAccessType('offline');
		$client->setPrompt('consent');
		$client->setIncludeGrantedScopes(true);
		$client->setApiFormatV2(2);

		$google = GoogleToken::where(['user_id' => $user->id])->first();
	  	$client->setAccessToken($google->access_token);
	  	if($client->isAccessTokenExpired()) { 
		    $client->refreshToken($client->getRefreshToken());		
			$google->access_token = json_encode($client->getAccessToken());
			$google->save();		 
		}
		$mybusiness = new \Google_Service_MyBusiness($client);
$l = new \Google_Service_MyBusiness_Location();
			$l->languageCode = 'en';
			$l->storeCode = Str::random(14);
			$l->locationName = $request->get('name');
			$l->primaryPhone = $request->get('phone');
			$category = new \Google_Service_MyBusiness_Category();
			$cats = json_decode($request->get('category'));
			$category->categoryId = $cats[0]->id;
			$category->displayName = $cats[0]->value;
			$services = json_decode($request->get('services'));
			$sert = [];
			for($i = 0; $i < count($services); $i++) {
				if(property_exists($services[$i], 'id') && $services[$i]->parent == $cats[0]->id) {
					array_push($sert, ["serviceTypeId" => $services[$i]->id, "displayName" => $services[$i]->value]);
				}
			}
			$category->serviceTypes = $sert;
			$l->setPrimaryCategory($category);
			$arrcate = [];
			for($i = 1; $i < count($cats); $i++) {
				$cate = new \Google_Service_MyBusiness_Category();
				$cate->categoryId = $cats[$i]->id;
				$cate->displayName = $cats[$i]->value;
				$sert1 = [];
				for($j = 0; $j < count($services); $j++) {
					if(property_exists($services[$j], 'id') && $services[$j]->parent == $cats[$i]->id) {
						array_push($sert1, ["serviceTypeId" => $services[$j]->id, "displayName" => $services[$j]->value]);
					}
				}
				$cate->serviceTypes = (count($sert1) > 0 ? $sert1 : null);
				$arrcate[$i - 1] = $cate;
			}
			if(count($arrcate) > 0)
				$l->setAdditionalCategories($arrcate);
			$l->websiteUrl = $request->get('website');
			$horarios = json_decode('['.$request->get('horarios').']');
			$arrh = [];
	    	foreach ($horarios[0] as $key => $value) {
	    		if(is_array($value)) {
	    			for($i = 0; $i < count($value); $i++) {
	    				$timep = new \Google_Service_MyBusiness_TimePeriod();
	    				$timep->openDay = strtoupper($key);
	    				$timep->closeDay = strtoupper($key);
	    				$timep->openTime = date('H:i',strtotime($value[$i]->ini));
	    				$timep->closeTime = date('H:i',strtotime($value[$i]->fin));
	    				array_push($arrh, $timep);
	    			}
	    		}
	    		else {
	    			$timep = new \Google_Service_MyBusiness_TimePeriod();
	    			$timep->openDay = strtoupper($key);
	    			$timep->closeDay = strtoupper($key);
	    			$timep->openTime = '00:00';
	    			$timep->closeTime = '24:00';
	    			array_push($arrh, $timep);
	    		}
	    	}
			$hoursb = new \Google_Service_MyBusiness_BusinessHours();
			$hoursb->setPeriods($arrh);
			$l->setRegularHours($hoursb);
			if($request->get('servicesa') != null) {
				$servarea = new \Google_Service_MyBusiness_ServiceAreaBusiness();
				$servarea->businessType = ($request->get('street') != null ? "CUSTOMER_AND_BUSINESS_LOCATION" : "CUSTOMER_LOCATION_ONLY");
				$places = new \Google_Service_MyBusiness_Places();
				$arrplaceinf = [];
				$servicesa = json_decode($request->get('servicesa'));
				for($i = 0; $i < count($servicesa); $i++) {
					$placeinfo = new \Google_Service_MyBusiness_PlaceInfo();
					$placeinfo->name = $servicesa[$i]->value;
					$queryFields = [
			            'query' => $servicesa[$i]->value,
			            'key' => 'KEY'
			        ];
			        $ch = curl_init();
			        curl_setopt($ch, CURLOPT_URL, "https://maps.googleapis.com/maps/api/place/textsearch/json?" . http_build_query($queryFields));
			        curl_setopt($ch, CURLOPT_USERAGENT, "php/curl");
			        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

			        $result = curl_exec($ch);
			        curl_close($ch);
			        $result = json_decode('['.$result.']');
					$placeinfo->placeId = $result[0]->results[0]->place_id;
					$arrplaceinf[$i] = $placeinfo;
				}
				$places->setPlaceInfos($arrplaceinf);
				$servarea->setPlaces($places);
				$l->setServiceArea($servarea);
			}
			$description = new \Google_Service_MyBusiness_Profile();
			$description->description = $request->get('description');
			$l->setProfile($description);
			$requestId = Str::random(40);
			$local = $mybusiness->accounts_locations->create($accountsList[0]->name, $l, ['requestId' => $requestId]);
```
I use the class provided by the Google My Business API

https://developers.google.com/my-business/samples/google-api-services-mybusiness-v4p6-php-rev-20200422-1.zip

**Comment by bshaffer** [comment] 2023-03-18 13:17
The 500 internal service error here implies that the issue is not with your code, but with the service itself. My guess is that this was a temporary problem with the My Business API that has since been resolved.

As this issue is very old, I'm closing it for now. Please open a new issue if you're still having this problem.

**Closed by bshaffer** 2023-03-18 13:17 UTC
Labels: type: question
