### ISSUE TITLE
An error occurs when trying to link GCP's Google Sheets API with a spreadsheet.

### ISSUE THREAD

**Issue by renhagino** [googleapis/google-api-php-client#2139] opened 2021-10-11 07:23 UTC
# summary

I created a project in GCP (Google Clous Platform) and created a service account with Google Sheets API (ver.4) enabled on the project.
　  
We gave the service account "owner" access rights, created an authentication key in .json format, placed it on the server, and shared the email address of the service account in the spreadsheet we wanted to access.

Then, when I tried to use PHP to call Google Sheets API and access the spreadsheet, I encountered the following error.
　
I have described below the current error message, the source code, and what I tried to do to solve it myself. Can anyone give me a solution or advice? Thank you very much.

## Current error messages
- The error occurs in the exception handling of function api_conect_manage() in the source code.
```
object(Google\Service\Exception)#101 (8) { ["errors":protected]=> NULL ["message":protected]=> string(98) "{"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}"
```
## Source Code
```php
//　Loading autoload.php
require_once('path/to/librarydirectory/google-api-php-client--PHP5.6/vendor/autoload.php');

use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;
use Google\Spreadsheet\SpreadsheetService;

//　initialization process
function  api_init(){
	　//　normal processing
	try{
		//Reads a json format file placed on the server.
		putenv('GOOGLE_APPLICATION_CREDENTIALS='/path-to-my-jsonkey/download-from-gcp-serviceaccount.json);
		// Prepare to connect to the Google client
		$client = new  Google_Client();
		
		//Authentication.
		$client->useApplicationDefaultCredentials();
	
		//　Setting the Application Name
		$client->setApplicationName("MySpreadsheet");//The application name can be anything.

		//If already have an access token, use that one.
		if (isset($_SESSION['service_token'])) {
			$client->setAccessToken($_SESSION['service_token']);
		}

		//　Write to the log file on the server when the process is successful.
		$this->exception_data_save("api_init() is normal processing");

		return  $client;
		
	// Exception handling
	}catch(Exception  $e){

		//processing to be written to the log on the server when processing becomes an error = exception processing.
		$this->exception_data_save("api_init()　is Exception handling. Make sure that the library is loaded correctly.い");

		var_dump($e);
		exit;
		return  false;
	}
	return  false;
	
}//function api_init() os ende

// API connection processing
function  api_conect(){
	try{
		//Reads the Json format key file placed on the server.
		putenv('GOOGLE_APPLICATION_CREDENTIALS='/path-to-my-jsonkey/download-from-gcp-serviceaccount.json');
		
		$client = new  Google_Client();
		$client->setApplicationName("MySpreadsheet");
		$client->useApplicationDefaultCredentials();
		
		// Setting Scopes 
		$client->setScopes([
			\Google_Service_Sheets::SPREADSHEETS,
			\Google_Service_Sheets::DRIVE,
			
			// Solution 1 The following scopes did not change the error content whether they were present or not.
			"https://spreadsheets.google.com/feeds",
			'https://www.googleapis.com/auth/drive',
			'https://www.googleapis.com/auth/drive.file',
			'https://www.googleapis.com/auth/spreadsheets',
		]);
		
		// Token-related processing
		$client->refreshTokenWithAssertion();
		if ($client->isAccessTokenExpired()) {
			$client->refreshTokenWithAssertion();
		} 
		$_SESSION['service_token'] = $client->getAccessToken();
		$obj_token = $client->getAccessToken();
		$accessToken=$obj_token;
		
		// Write to the log file on the server when the process is successful
		$this->exception_data_save("api_conect() is normal processing.");
		return  $accessToken; //Return an access token
			}catch(Exception $e){
			
		//Process to write to the log on the server when the process becomes an error = exception handling.
		$this->exception_data_save("function api_conect() is Exception handling.");
		return  false;
	}
	return  false;
}////End of API connection process

//API connection management process
function api_conect_manage($sheet_name=NULL,$current_date=NULL,&$input_data=array()){
	
	//If function api_init() works correctly and the access token is successfully obtained by api_conect()
	if(($client=$this->api_init())!==false && ($access_token=$this->api_conect($client))!==false){
	
	    // Start the try, catch process
	    try{
			$serviceRequest = new  DefaultServiceRequest($access_token['access_token']);
			ServiceRequestFactory::setInstance($serviceRequest);
			$spreadsheetService = new  Google_Service_Sheets($client);
			$spreadsheetId = 'my spreadsheetId';
			$sheetId = 'my sheetID'
			
			//　Solution 2 ->I tried passing $sheetId as the argument of the get () part, but the error was not resolved.
			$spreadsheetFeed = $spreadsheetService->spreadsheets->get($spreadsheetId);
			
		// Exception handling.
		}(catch Exeption $e){
			//Process to write to the log on the server when the process becomes an error = exception handling.	
			$this->exception_data_save("The try catch process in api_conect_mange() is exception handling.",$input_data);
			
			// This is where the error occurs this time. => （Invalid OAuth scope or ID token audience provided）
			var_dump($e);
			exit;
			return false;
		
		}//End of try,catch
		
	}//End of if branch
	
}//End of function api_conect_manage()
```

## What I tried to solve the problem
- I tested adding and disabling scopes to setScopes() in function api_conect(), but the error message remained the same.（The comment section called "Solution 1）

-   changed the argument of ->($spreadsheetId) in the spreadsheet acquisition part to sheetI, but there was no change in the error message. (Comment part called "Solution 2")

## Libraries and external services I am using
- google-api-php-client--PHP5.6  v2.10.0
https://github.com/googleapis/google-api-php-client/releases

- Google Cloud Platform
https://console.cloud.google.com/

## Pages used for reference
- php google api client
https://github.com/googleapis/google-api-php-client

- Migrate from Sheets API  from  v3 https://developers.google.com/sheets/api/guides/migration#v4-api_5

- PHP QuickStart
https://developers.google.com/sheets/api/quickstart/php

**Comment by saranshdhingra** [comment] 2023-05-31 10:54
Hi @renhagino 
Sorry for the late reply on this.

I tried the following simple piece of code and everything seems to work for me:
```
$sheetId = "SPREADSHEET_ID";
$service = new \Google_Service_Sheets($client);
$feed = $service->spreadsheets->get($sheetId);
echo $feed->getProperties()->getTitle();
```

It should be noted that I only used the `https://www.googleapis.com/auth/drive` and I didn't receive any exception.
Perhaps there was a temporary issue with the auth setup?
Perhaps changing the auth technique(service account to oauth) would help in identifying the issue.

Since this is very old and I can't reproduce it, I'll be closing this for now, but if you feel this is not yet resolved, please reopen this.

**Closed by saranshdhingra** 2023-05-31 10:54 UTC
Labels: type: question
